# -*- coding: utf-8 -*-
"""Chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnBJBV-IbE8F4annuppXpzdUTaz5TzWU
"""

# chatbot.py

def simple_chatbot(user_query):
    if user_query.lower() == "what is the total revenue?":
        return "The total revenue is $100 million."  # Replace with actual data
    elif user_query.lower() == "how has net income changed over the last year?":
        return "The net income has increased by 5% over the last year."  # Replace with actual data
    elif user_query.lower() == "what are the total assets?":
        return "The total assets are $500 million."  # Replace with actual data
    elif user_query.lower() == "what is the debt-to-asset ratio?":
        return "The debt-to-asset ratio is 40%."  # Replace with actual data
    else:
        return "Sorry, I can only provide information on predefined queries."

# Main loop to test the chatbot
if __name__ == "__main__":
    print("Welcome to the Financial Chatbot! Ask your financial queries.")
    while True:
        query = input("You: ")
        if query.lower() == "exit":
            print("Chatbot: Thank you! Have a great day!")
            break
        response = simple_chatbot(query)
        print("Chatbot:", response)